### ISSUE TITLE
M300 frequency and tone queue not working

### ISSUE THREAD

**Issue by Dominik-1980** [Pmatsol58/VyperCE6.1#11]
### Bug Description

M300 always plays the same tone. I can change duration with P, but frequency with S doesn't work.
Also the tone queue doesn't work. 
I have a list of M300 commands at the End-gCode, to play a melody, but it just plays one tone.
Always the same beep with the same frequency as the touchscreen input uses...

### Version of CR6Community Firmware

Anycubic Vyper CE6.1c

**Comment by Pmatsol58** [comment]
The M300 beep uses the tone output of the display which is a fixed frequency, I need to look at bringing it back to the onboard speaker which can have frequency set.

**Comment by smcbride-ca** [comment]
[This commit](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.1d/commit/b49f8c4315c130473a49057260fa1f6880cae1fa) fixes the issue. If these changes are made we can get sound working properly

**Comment by Pmatsol58** [comment]
Committed.
