### ISSUE TITLE
[FR] Anycubic Kobra

### ISSUE THREAD

**Issue by ckarcz** [Pmatsol58/VyperCE6.1#16]
### Are you looking for hardware support?

Any ideas on getting this to work on the Kobra Max (which is basically a large Vyper)? 
Would simply updating the Configuration.h work?

### Describe the feature you want

Anycubic Kobra MAX support.

**Comment by rommulaner** [comment]
I don't know the exact data of the Kobra Max, but if it is the same setup and parts it is easily possible, yes.

**Comment by Pmatsol58** [comment]
I believe the motherboard is different and so it may not work. Anycubic have not released hardware details or source as far as I know and I do not have access to a Max and so cannot support it.

**Comment by ckarcz** [comment]
the motherboard for the Vyper is a TriGorilla+ and the motherboard for the
Kobra appears to be a Trigorilla Pro A.

**Comment by rommulaner** [comment]
Has the Kobra Max the same board as the Kobra?

**Comment by Pmatsol58** [comment]
It is possible but without a Kobra to work with it will not happen.
Development on this version has ceased, see https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2
