### ISSUE TITLE
[BUG] 6.1E Temperature drops during auto leveling 

### ISSUE THREAD

**Issue by pasha4ur** [Pmatsol58/VyperCE6.1#20]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

Hello.

6.1E LA Direct 7x7.

I preheat a printer to 240/104 and start autoleveling with same temps in the autoleveling settings.

Looks like I found a bug. Printer doesn't hold bed temperature when makes autoleveling.
If I set the bed temp to 104* (7x7 autoleveling) then at the middle of process it will be around 97* and at the end of process - around  94*.
The nozzle temperature 230 -> 226.

### Version of CR6Community Firmware

6.1e Vyper

### Printer model

Other (I will explain below)

### Motherboard

Other (I will explain below)

### Display

Other (I will explain below)

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by Pmatsol58** [comment]
Development on this version has ceased, see https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2
