### ISSUE TITLE
[FR] BL touch for Anycubic Vyper?

### ISSUE THREAD

**Issue by pasha4ur** [Pmatsol58/VyperCE6.1#21]
### Describe the feature you want

Hello

Is there any way to add BL touch support to this firmware? Maybe with saving Z-endstops. I know a former embedded systems developer. Perhaps he can help. I saw a chip from ST on the head board.

![Screenshot 2023-03-19 024556](https://user-images.githubusercontent.com/8062377/226147706-7997b303-f73f-4d8e-92d5-fca38184dca5.jpg)
![335227568_1206506539979786_5275161576343321282_n](https://user-images.githubusercontent.com/8062377/226147714-ba5b77db-2a8d-4474-8c1d-b695bb012a8d.jpg)
![335910455_757168742707618_569471169228192252_n](https://user-images.githubusercontent.com/8062377/226147717-d51dcacf-4458-42d0-a174-c300e075c122.jpg)
![336234440_130566926452305_7161786061358697911_n](https://user-images.githubusercontent.com/8062377/226147718-39d9fb54-ab60-43dd-9f4b-6ca27c005860.jpg)
![336373809_228083636447784_371402228869860850_n](https://user-images.githubusercontent.com/8062377/226147719-d37742a1-c3a8-4e1f-aba4-d760b7c6f2ca.jpg)

**Comment by Pmatsol58** [comment]
Marlin has support for BL-Touch provided pins can be found for activation and sensing. 
Development on this version has ceased, see https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2
