### ISSUE TITLE
Please edit your README to stop pointing at the CR6Community Repo and Discord

### ISSUE THREAD

**Issue by Thinkersbluff** [Pmatsol58/VyperCE6.1#22]
### Did you test the latest `extui` code or prerelease?

Yes, and the problem still exists.

### Bug Description

When you fork a repo, it defaults to keeping the original README.
The CR6Community README files point to CR6Community help resources, but the CR6Community is NOT participating in your project and is NOT supporting your users.  Your users do not know that and are posting PRs and help requests asking for changes to the CR6Community firmware, when encountering problems with your code.

Please delete the CR6Community links from your README.

### Bug Timeline

na

### Expected behavior

na

### Actual behavior

na

### Steps to Reproduce

na

### Version of CR6Community Firmware

na

### Printer model

Creality CR-6 SE

### Motherboard

Creality v4.5.2

### Display

Creality CR-6 stock touch screen

### Mods

na

### Add-ons

na

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by rommulaner** [comment]
Done.

**Comment by Pmatsol58** [comment]
Done. Apologies for not addressing this earlier.
