### ISSUE TITLE
Printing from host (Octoprint) doesn't show progress

### ISSUE THREAD

**Issue by Dominik-1980** [Pmatsol58/VyperCE6.1#6]
### Bug Description

When printing from Octoprint no progress is shown in the display. 
It stays at 0%

Vyper 6.1c

### Printer model

Anycubic Vyper

### Host Software

OctoPrint

**Comment by Pmatsol58** [comment]
If I remember this requires a setting in the slicer or an octoprint plugin, check out this blog post from Sebastiaan: https://damsteen.nl/blog/2021/03/13/estimated-time-remaining-with-the-cr6-community-firmware

**Comment by yasars** [comment]
instead of the name it says "printing from host", can we get that fixed?

**Comment by Pmatsol58** [comment]
I don't use octoprint so I'm not sure if name can be used in place of "printing from host", there probably is a way of doing it but I just don't know.

**Comment by Dominik-1980** [comment]
For the record.
I use the "Detailed Progress" Plugin. Works like a charm! 👍🏼
